/*
 * This source file was generated by the Gradle 'init' task
 */
package com.harrison.httpserver;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import com.harrison.httpserver.http.HttpParser;

import static org.junit.jupiter.api.Assertions.*;

import java.io.InputStream;

@TestInstance(TestInstance.Lifecycle.PER_CLASS) // ??
class HttpParserTest {
  private HttpParser httpParser;

  @BeforeAll
  private void beforeClass() {
    httpParser = new HttpParser();
  }

  @Test
  void parseHttpRequest() {
    // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }
}
