/*
 * This source file was generated by the Gradle 'init' task
 */
package com.harrison.httpserver;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.ServerSocket;
import java.net.Socket;

import com.harrison.httpserver.config.Configuration;
import com.harrison.httpserver.config.ConfigurationManager;

public class App {
  public String getGreeting() {
    return "Hello!";
  }

  public static void main(String[] args) {
    System.out.println("Server starting...");

    ConfigurationManager.getInstance().loadConfigurationFile("src/main/resources/server_config.json");
    Configuration conf = ConfigurationManager.getInstance().getCurrentConfiguration();

    System.out.println("Port: " + conf.getPort());
    System.out.println("Webroot: " + conf.getWebroot());

    try {
      ServerSocket serverSocket = new ServerSocket(conf.getPort());
      Socket socket = serverSocket.accept();
      InputStream inputStream = socket.getInputStream();
      OutputStream outputStream = socket.getOutputStream();

      String html = "<html><head><title>Test website</title></head><body><h1>Welcome to the simple java server</h1></body></html>";
      final String CRLF = "\n\r";
      String response = "HTTP/1.1 200 OK" + CRLF + // HTTP_Version Response_Code Response_Message
          "Content-Length: " + html.getBytes().length + CRLF + // Header
          CRLF +
          html +
          CRLF + CRLF;

      outputStream.write(response.getBytes());

      inputStream.close();
      outputStream.close();
      socket.close();
      serverSocket.close();
    } catch (IOException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
  }
}
