/*
 * This source file was generated by the Gradle 'init' task
 */
package com.harrison.httpserver;

import java.io.IOException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harrison.httpserver.config.Configuration;
import com.harrison.httpserver.config.ConfigurationManager;
import com.harrison.httpserver.core.ServerListenerThread;

public class App {
  private final static Logger LOGGER = LoggerFactory.getLogger(App.class);

  public static void main(String[] args) {
    LOGGER.info("Server starting...");

    ConfigurationManager.getInstance().loadConfigurationFile("src/main/resources/server_config.json");
    Configuration conf = ConfigurationManager.getInstance().getCurrentConfiguration();

    LOGGER.info("Port: " + conf.getPort());
    LOGGER.info("Webroot: " + conf.getWebroot());

    try {
      ServerListenerThread listener = new ServerListenerThread(conf.getPort(), conf.getWebroot());
      listener.start();
    } catch (IOException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
  }
}
