/*
 * This source file was generated by the Gradle 'init' task
 */
package com.harrison.httpserver;

import java.io.IOException;

import com.harrison.httpserver.config.Configuration;
import com.harrison.httpserver.config.ConfigurationManager;
import com.harrison.httpserver.core.ServerListenerThread;

public class App {
  public String getGreeting() {
    return "Hello!";
  }

  public static void main(String[] args) {
    System.out.println("Server starting...");

    ConfigurationManager.getInstance().loadConfigurationFile("src/main/resources/server_config.json");
    Configuration conf = ConfigurationManager.getInstance().getCurrentConfiguration();

    System.out.println("Port: " + conf.getPort());
    System.out.println("Webroot: " + conf.getWebroot());

    try {
      ServerListenerThread listener = new ServerListenerThread(conf.getPort(), conf.getWebroot());
      listener.start();
    } catch (IOException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
  }
}
